if (!require("terra")) install.packages("terra")
if (!require("remotes")) install.packages("remotes")
if (!require("units")) install.packages("units")
if (!require("sf")) install.packages("sf")
library(remotes)
library(terra)
library(units)
library(sf)
if (!require("rspat")) remotes::install_github("rspatial/rspat")
library(rspat)
h <- spat_data('houses2000')
writeVector(h, "data/california/houses2000.shp", overwrite=TRUE)
